Models/ErrorViewModel.cs
namespace Piadas.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/piadas.cs
namespace Piadas.Models;

public class piadas
{
    public int id { get; set; }
    public string pergunta { get; set; }
    public string resposta { get; set; }

    public piadas()
    {
        
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Piadas.Models;

namespace Piadas.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/PiadaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Piadas.Data;
using Piadas.Models;

namespace Piadas.Controllers
{
    public class PiadaController : Controller
    {
        private readonly PiadasDbContext _context;

        public PiadaController(PiadasDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Busca()
        {
            return View();
        }
        
        public async Task<IActionResult> ShowSearchResults(String TermoDeBusca)
        {
            List<piadas> piadoca = await _context.piadas.Where(f => f.pergunta.Contains(TermoDeBusca)).ToListAsync();
            return View("Index", piadoca);
        }
        // GET: Piada
        public async Task<IActionResult> Index()
        {
            return View(await _context.piadas.ToListAsync());
        }

        // GET: Piada/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var piadas = await _context.piadas
                .FirstOrDefaultAsync(m => m.id == id);
            if (piadas == null)
            {
                return NotFound();
            }

            return View(piadas);
        }

        // GET: Piada/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Piada/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,pergunta,resposta")] piadas piadas)
        {
            if (ModelState.IsValid)
            {
                _context.Add(piadas);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(piadas);
        }

        // GET: Piada/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var piadas = await _context.piadas.FindAsync(id);
            if (piadas == null)
            {
                return NotFound();
            }
            return View(piadas);
        }

        // POST: Piada/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,pergunta,resposta")] piadas piadas)
        {
            if (id != piadas.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(piadas);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!piadasExists(piadas.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(piadas);
        }

        // GET: Piada/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var piadas = await _context.piadas
                .FirstOrDefaultAsync(m => m.id == id);
            if (piadas == null)
            {
                return NotFound();
            }

            return View(piadas);
        }

        // POST: Piada/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var piadas = await _context.piadas.FindAsync(id);
            if (piadas != null)
            {
                _context.piadas.Remove(piadas);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool piadasExists(int id)
        {
            return _context.piadas.Any(e => e.id == id);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Piada/Busca.cshtml
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}
<div class="row">
    <div class="col-md-4">
        <form asp-action="ShowSearchResults">
            <div class="form-group">
                <label for="TermoDeBusca" class="control-label"></label>
                <input name="TermoDeBusca" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Busca" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

Views/Piada/Create.cshtml
@model Piadas.Models.piadas

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>piadas</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="pergunta" class="control-label"></label>
                <input asp-for="pergunta" class="form-control" />
                <span asp-validation-for="pergunta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="resposta" class="control-label"></label>
                <input asp-for="resposta" class="form-control" />
                <span asp-validation-for="resposta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Piada/Delete.cshtml
@model Piadas.Models.piadas

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>piadas</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.pergunta)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.pergunta)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.resposta)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.resposta)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Piada/Details.cshtml
@model Piadas.Models.piadas

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>piadas</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.pergunta)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.pergunta)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.resposta)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.resposta)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Piada/Edit.cshtml
@model Piadas.Models.piadas

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>piadas</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="pergunta" class="control-label"></label>
                <input asp-for="pergunta" class="form-control" />
                <span asp-validation-for="pergunta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="resposta" class="control-label"></label>
                <input asp-for="resposta" class="form-control" />
                <span asp-validation-for="resposta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Piada/Index.cshtml
@model IEnumerable<Piadas.Models.piadas>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.pergunta)
            </th>
      
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.pergunta)
            </td>
           
            <td>
                <a asp-action="Edit" asp-route-id="@item.id">Modificar</a> |
                <a asp-action="Details" asp-route-id="@item.id">Ver resposta</a> |
                <a asp-action="Delete" asp-route-id="@item.id">Remover</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Piadas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Piadas.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Piadas</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Piada" asp-action="Index">Piadas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Piada" asp-action="Busca">Busca</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - Piadas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>